# Generated by Django 6.0.4 on 2026-04-12 07:58

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessionViolationReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_violations', models.IntegerField(default=0)),
                ('high_severity_violations', models.IntegerField(default=0)),
                ('medium_severity_violations', models.IntegerField(default=0)),
                ('low_severity_violations', models.IntegerField(default=0)),
                ('tab_switches', models.IntegerField(default=0)),
                ('face_not_visible_seconds', models.IntegerField(default=0)),
                ('looking_away_instances', models.IntegerField(default=0)),
                ('speaking_instances', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('flagged', 'Flagged for Review')], default='in_progress', max_length=20)),
                ('proctoring_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation_report', to='exams.studentexamattempt')),
            ],
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='ProctorLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('violation_type', models.CharField(choices=[('face_not_visible', 'Face Not Visible'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away from Screen'), ('tab_switch', 'Tab/Window Switched'), ('multiple_speakers', 'Multiple Speakers Detected'), ('background_noise', 'Suspicious Background Noise'), ('mobile_phone_detected', 'Mobile Phone Detected'), ('notebook_detected', 'Notebook Detected')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='proctor_logs/')),
                ('audio_snapshot', models.FileField(blank=True, null=True, upload_to='proctor_audio/')),
                ('details', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='exams.studentexamattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['attempt', 'timestamp'], name='proctoring__attempt_c87c5a_idx'), models.Index(fields=['violation_type', 'timestamp'], name='proctoring__violati_9622f6_idx')],
            },
        ),
    ]
