# Generated by Django 4.2.27 on 2026-02-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('phone_detected', 'Phone Detected'), ('looking_away', 'Looking Away')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='proctor_snapshots/')),
                ('details', models.TextField(blank=True, help_text='JSON or text details about the violation')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='exams.studentexamattempt')),
            ],
        ),
    ]
